# -*- coding: utf-8 -*-
{
    "name": "User Access Restrict",
    "version": "18.0.1.0.0",
    "category": "Warehouse",
    "summary": "Dynamic warehouse based access control",
    "description": "Manage user permissions per warehouse using custom access types.",
    "author": "Acrisign Techno Solutions",
    "company": "Acrisign Techno Solutions ",
    "maintainer": "Acrisign Techno Solutions",
    "website": "https://www.acrisign.com.br",
    "depends": ["stock", "sale_management", "purchase"],
    "data": [
        "security/user_groups.xml",
        "security/record_rules.xml",
        "security/ir.model.access.csv",
        "views/res_users_views.xml",
        "i18n/en.po",
        "i18n/ar.po",
    ],
    "license": "AGPL-3",
    "installable": True,
    "auto_install": False,
    "application": False,
}
